### PR TITLE
Add KLS to database

### PR DESCRIPTION
**Pull request by lemois-1337**
**Project:** Karlsen
**App repository:** https://github.com/karlsen-network/app-karlsen
**Coin type:** 121337 as registered in https://github.com/satoshilabs/slips/blob/master/slip-0044.md

### CODE REVIEW

**Comment by tdejoigny-ledger** [comment]
Hi @lemois-1337 ty for you PR
But it seems that Flex device is missing

**Comment by lemois-1337** [comment]
@tdejoigny-ledger Added next-gen Ledger Flex device, was forgotten in first commit, force pushed.

**Comment by tdejoigny-ledger** [comment]
sorry @lemois-1337 my bad, I missed that you have also nanoS. NanoS shall be removed. 
New app should not be deployed on NanoS (EOL product). You can also remove NanoS in the[ledger_app.toml](https://github.com/karlsen-network/app-karlsen/blob/main/ledger_app.toml)

**Comment by lemois-1337** [comment]
@tdejoigny-ledger I've removed NanoS from this PR (force-pushed). I've fixed it in [ledger_app.toml](https://github.com/karlsen-network/app-karlsen/blob/main/ledger_app.toml) as well and thanks for letting me know.

**Review by tdejoigny-ledger — APPROVED** [review]

**Comment by tdejoigny-ledger** [comment]
perfect ty @lemois-1337

**Pull request merged**
