### PR TITLE
Add Seed Tool application to database

### PR DESCRIPTION
**Pull request by aido**
https://github.com/aido/app-seed-tool

### CODE REVIEW

**Comment by tdejoigny-ledger** [comment]
@aido ty for your PR. We need to check internally if we can integrate this tool in our app store.

**Comment by aido** [comment]
Hi @tdejoigny-ledger,

If it helps with auditing please be aware that ~40% (the BIP39 check parts) of the code in the [app-seed-tool](https://github.com/aido/app-seed-tool) application is a direct copy of the existing [app-recovery-check](https://github.com/LedgerHQ/app-recovery-check) application written by Ledger. Another ~40% (the Shamir's Secret Shares generation parts) is a direct copy of [bc-sskr](https://github.com/BlockchainCommons/bc-sskr) which has received an independent [security audit](https://github.com/BlockchainCommons/bc-sskr/blob/master/SECURITY-REVIEW.md). The remaining ~20% (the Shamir's Secret Sharing UI parts) may not be a direct copy of  the [app-recovery-check](https://github.com/LedgerHQ/app-recovery-check) application but is heavily 'inspired' by it.

**Comment by aido** [comment]
Hi @tdejoigny-ledger ,

Any movement on this?

**Comment by tdejoigny-ledger** [comment]
@aido the discussion is ongoing internally...

**Comment by tdejoigny-ledger** [comment]
Hi @aido, could you please rebase your PR ? ty

**Comment by xchapron-ledger** [comment]
@aido Can you rebase locally and push force? When using the rebase feature of Github you shouldn't use the "rebase with merge option" as we want to keep a linear git history.

**Comment by aido** [comment]
> @aido Can you rebase locally and push force? When using the rebase feature of Github you shouldn't use the "rebase with merge option" as we want to keep a linear git history.

Apologies. I think I fixed that now. I thought the GitHub options would help me but they worked against me instead. :-)

**Review by tdejoigny-ledger — APPROVED** [review]

**Pull request merged**
