### PR TITLE
fix: Update app-load-params-db.json for Acre app

### PR DESCRIPTION
**Pull request by n4l5u0r**
alignement of the required derivation path for Acre App

### CODE REVIEW

**Comment by tdejoigny-ledger** [comment]
@n4l5u0r the allowed paths used in the app shall be mentioned

**Comment by n4l5u0r** [comment]
> @n4l5u0r the allowed paths used in the app shall be mentioned
@tdejoigny-ledger we are using PSBT within Acre and need to access the master fingerprint for these transactions
.

**Comment by tdejoigny-ledger** [comment]
@n4l5u0r ok could you please just rebase you PR and I will merge it

**Comment by n4l5u0r** [comment]
@tdejoigny-ledger PR rebased

**Review by tdejoigny-ledger — APPROVED** [review]

**Pull request merged**
