### PR TITLE
Add `flex` for xahau

### PR DESCRIPTION
**Pull request by dangell7**

### CODE REVIEW

**Comment by tdejoigny-ledger** [comment]
@dangell7 ty for your PR.
Could you please remove "nanos" from target list ? (and from your ledger toml if not already the case). This product is EOL.

**Comment by tdejoigny-ledger** [comment]
ty for the udpate. Could you please rebase and then I will merge? @dangell7

**Comment by tdejoigny-ledger** [comment]
sorry @dangell7 still some issue with your rebase

**Comment by dangell7** [comment]
> sorry @dangell7 still some issue with your rebase

https://github.com/LedgerHQ/ledger-app-database/pull/283

**Pull request closed without merging**
